Experimental file checks

diff --git a/run_onchange_apply_packages.sh.tmpl b/run_onchange_apply_packages.sh.tmpl
--- a/run_onchange_apply_packages.sh.tmpl
+++ b/run_onchange_apply_packages.sh.tmpl
@@ -113,6 +113,14 @@ brew upgrade
 
 printf "\n[${executor}] ${BBlue}INFO${Color_Off} - Evaluating installables via brew bundle...\n"
 
+[[ $( cat <<EOF | wc -l ) -gt 0 ]] && echo 'FAIL' && exit 1
+{{ range .packages.files -}}
+$(  if [[ ! -f {{ . }} && ! -d {{ . }} ]]; then
+        printf "\n[${executor}] ${BBlue}ERROR${Color_Off} - Unable to locate {{ . | quote }} \n"
+    fi )
+{{ end -}}
+EOF
+
 cat <<EOF
 
 {{ range .packages.homebrew.taps -}}
@@ -158,8 +166,6 @@ $(  if [[ -f {{ . }} ]]; then
         cat {{ . }}
     elif [[ -d {{ . }} ]]; then
         find {{ . }} -name '*.Brewfile' -exec cat {} \; | sort -u
-    else
-        printf "${Red}Unable to locate: {{ . }} ${Color_Off}\n"
     fi )
 {{ end -}}
 
@@ -170,9 +176,13 @@ printf "\n[${executor}] ${BBlue}INFO${Color_Off} - Executing brew bundle...\n"
 brew bundle install --upgrade --cleanup --file=/dev/stdin <<EOF
 
 {{ range .packages.homebrew.taps -}}
-$( [[ -f {{ . }} ]] && cat {{ . }} | grep '^tap' | sort -u )
-$( [[ -d {{ . }} ]] && find {{ . }} -name '*.Brewfile' -exec cat {} \; | grep '^tap' | sort -u )
-$( [[ ! -f {{ . }} && ! -d {{ . }} ]] && echo 'tap {{ . | quote }}' )
+$(  if [[ -f {{ . }} ]]; then
+        cat {{ . }} | grep '^tap' | sort -u
+    elif [[ -d {{ . }} ]]; then
+        find {{ . }} -name '*.Brewfile' -exec cat {} \; | grep '^tap' | sort -u
+    else
+        echo 'tap {{ . | quote }}'
+    fi )
 {{ end -}}
 
 {{ range .packages.homebrew.formulae -}}
@@ -204,8 +214,11 @@ vscode {{ . | quote }}
 {{ end -}}
 
 {{ range .packages.files -}}
-$( [[ -f {{ . }} ]] && cat {{ . }} )
-$( [[ -d {{ . }} ]] && find {{ . }} -name '*.Brewfile' -exec cat {} \; | sort -u )
+$(  if [[ -f {{ . }} ]]; then
+        cat {{ . }}
+    elif [[ -d {{ . }} ]]; then
+        find {{ . }} -name '*.Brewfile' -exec cat {} \; | sort -u
+    fi )
 {{ end -}}
 
 EOF
