Experimental file checks 11

diff --git a/run_onchange_apply_packages.sh.tmpl b/run_onchange_apply_packages.sh.tmpl
--- a/run_onchange_apply_packages.sh.tmpl
+++ b/run_onchange_apply_packages.sh.tmpl
@@ -119,17 +119,17 @@ mapfile -t input_files < <(
 {{ end -}}
 )
 
-fail='false'
+fail="false"
 if [[ -z ${input_files+x} && ${#input_files[@]} -gt 0 ]]; then
     for i_f in "${input_files[@]}"; do
         if [[ ! -e ${i_f} ]]; then
             printf "\n[${executor}] ${BRed}ERROR${Color_Off} - Unable to locate ${i_f} \n"
-            fail='true'
+            fail="true"
         fi
     done
 fi
 
-[[ "${fail}" == 'true' ]] && exit 1 || unset fail
+[[ "${fail}" == "true" ]] && exit 1 || unset fail
 
 BREWFILE="
 {{ range .packages.homebrew.taps -}}
