Added desktop env checks

diff --git a/run_onchange_apply_packages.sh.tmpl b/run_onchange_apply_packages.sh.tmpl
--- a/run_onchange_apply_packages.sh.tmpl
+++ b/run_onchange_apply_packages.sh.tmpl
@@ -175,94 +175,116 @@ rm -fv "${cache}"/requirements*
 
 printf "\n[${executor}] ${BBlue}INFO${Color_Off} - Evaluating GNOME extensions...\n"
 
-cat <<EOF > "${cache}"/registry_wanted_gnome_extensions.txt
+
+if ! command -v gnome-shell &> /dev/null; then
+    printf "[${executor}] ${BRed}ERROR${Color_Off} - A non-Gnome desktop environment was detected, where Gnome extensions are not supported"
+
+else
+
+    printf "[${executor}] ${BBlue}INFO${Color_Off} - Testing connection with https://extensions.gnome.org/..."
+    if ! curl -fLsS --retry 5 -o /dev/null --head "https://extensions.gnome.org/"; then
+        printf "[${executor}] ${BRed}ERROR${Color_Off} - Connection unsuccessful."
+        printf "[${executor}] ${BRed}ERROR${Color_Off} - This usually happens when https://extensions.gnome.org/ website is down."
+        printf "[${executor}] ${BRed}ERROR${Color_Off} - Please try again later (or disable the module temporarily)"
+
+    else
+        printf "[${executor}] ${BBlue}INFO${Color_Off} - Connection successful, proceeding."
+
+
+        cat <<EOF > "${cache}"/registry_wanted_gnome_extensions.txt
 {{ range .packages.gnome_extensions -}}
 {{ . }}
 {{ end -}}
 EOF
 
-declare -a failed_uninstall=()
-declare -a failed_install=()
+        GNOME_VER=$(gnome-shell --version | sed 's/[^0-9]*\([0-9]*\).*/\1/')
+        printf "[${executor}] ${BBlue}INFO${Color_Off} - Gnome version: ${GNOME_VER}"
 
-if [[ -f "${cache}"/registry_present_gnome_extensions.txt ]]; then
+        declare -a failed_uninstall=()
+        declare -a failed_install=()
 
-    # unique lines found in second input compared to first input
-    mapfile -t gnome_extensions_to_install < <( \grep -Fxvf "${cache}"/registry_present_gnome_extensions.txt "${cache}"/registry_wanted_gnome_extensions.txt )
-    mapfile -t gnome_extensions_to_uninstall < <( \grep -Fxvf "${cache}"/registry_wanted_gnome_extensions.txt "${cache}"/registry_present_gnome_extensions.txt )
+        if [[ -f "${cache}"/registry_present_gnome_extensions.txt ]]; then
 
-    if [[ ! -z ${gnome_extensions_to_uninstall+x} && ${#gnome_extensions_to_uninstall[@]} -gt 0 ]]; then
-        for getu in "${gnome_extensions_to_uninstall[@]}"; do
-            # Uninstall
-            # Remove from registry
-            # Remove empty lines
-            if gdbus call --session \
-            --dest org.gnome.Shell.Extensions \
-            --object-path /org/gnome/Shell/Extensions \
-            --method org.gnome.Shell.Extensions.UninstallExtension \
-            "${getu}"; then
-                sed -i "/${getu}/d" "${cache}"/registry_present_gnome_extensions.txt
-                sed -i '/^$/d' "${cache}"/registry_present_gnome_extensions.txt
-            else
-                failed_uninstall+=( "${getu}" )
+            # unique lines found in second input compared to first input
+            mapfile -t gnome_extensions_to_install < <( \grep -Fxvf "${cache}"/registry_present_gnome_extensions.txt "${cache}"/registry_wanted_gnome_extensions.txt )
+            mapfile -t gnome_extensions_to_uninstall < <( \grep -Fxvf "${cache}"/registry_wanted_gnome_extensions.txt "${cache}"/registry_present_gnome_extensions.txt )
+
+            if [[ ! -z ${gnome_extensions_to_uninstall+x} && ${#gnome_extensions_to_uninstall[@]} -gt 0 ]]; then
+                for getu in "${gnome_extensions_to_uninstall[@]}"; do
+                    # Uninstall
+                    # Remove from registry
+                    # Remove empty lines
+
+                    if gdbus call --session \
+                    --dest org.gnome.Shell.Extensions \
+                    --object-path /org/gnome/Shell/Extensions \
+                    --method org.gnome.Shell.Extensions.UninstallExtension \
+                    "${getu}" ; then
+                        sed -i "/${getu}/d" "${cache}"/registry_present_gnome_extensions.txt
+                        sed -i '/^$/d' "${cache}"/registry_present_gnome_extensions.txt
+                    else
+                        failed_uninstall+=( "${getu}" )
+                    fi
+                done
             fi
-        done
-    fi
 
-    if [[ ! -z ${gnome_extensions_to_install+x} && ${#gnome_extensions_to_install[@]} -gt 0 ]]; then
-        for geti in "${gnome_extensions_to_install[@]}"; do
-            # Install
-            # Add to registry
-            if gdbus call --session \
-            --dest org.gnome.Shell.Extensions \
-            --object-path /org/gnome/Shell/Extensions \
-            --method org.gnome.Shell.Extensions.InstallRemoteExtension \
-            "${geti}"; then
-                echo "${geti}" | tee -a "${cache}"/registry_present_gnome_extensions.txt > /dev/null
-            else
-                failed_install+=( "${geti}" )
+            if [[ ! -z ${gnome_extensions_to_install+x} && ${#gnome_extensions_to_install[@]} -gt 0 ]]; then
+                for geti in "${gnome_extensions_to_install[@]}"; do
+                    # Install
+                    # Add to registry
+
+                    if gdbus call --session \
+                    --dest org.gnome.Shell.Extensions \
+                    --object-path /org/gnome/Shell/Extensions \
+                    --method org.gnome.Shell.Extensions.InstallRemoteExtension \
+                    "${geti}" ; then
+                        echo "${geti}" | tee -a "${cache}"/registry_present_gnome_extensions.txt > /dev/null
+                    else
+                        failed_install+=( "${geti}" )
+                    fi
+                done
             fi
-        done
-    fi
 
-else
+        else
 
-    # Read file lines without inline comments and pipe them one by one to cmd
-    mapfile -t gnome_extensions_to_install < <( cat "${cache}"/registry_wanted_gnome_extensions.txt )
+            # Read file lines without inline comments and pipe them one by one to cmd
+            mapfile -t gnome_extensions_to_install < <( cat "${cache}"/registry_wanted_gnome_extensions.txt )
 
-    if [[ ! -z ${gnome_extensions_to_install+x} && ${#gnome_extensions_to_install[@]} -gt 0 ]]; then
-        for geti in "${gnome_extensions_to_install[@]}"; do
-            # Install
-            # Add to registry
-            if gdbus call --session \
-            --dest org.gnome.Shell.Extensions \
-            --object-path /org/gnome/Shell/Extensions \
-            --method org.gnome.Shell.Extensions.InstallRemoteExtension \
-            "${geti}"; then
-                echo "${geti}" | tee -a "${cache}"/registry_present_gnome_extensions.txt > /dev/null
-            else
-                failed_install+=( "${geti}" )
+            if [[ ! -z ${gnome_extensions_to_install+x} && ${#gnome_extensions_to_install[@]} -gt 0 ]]; then
+                for geti in "${gnome_extensions_to_install[@]}"; do
+                    # Install
+                    # Add to registry
+                    if gdbus call --session \
+                    --dest org.gnome.Shell.Extensions \
+                    --object-path /org/gnome/Shell/Extensions \
+                    --method org.gnome.Shell.Extensions.InstallRemoteExtension \
+                    "${geti}"; then
+                        echo "${geti}" | tee -a "${cache}"/registry_present_gnome_extensions.txt > /dev/null
+                    else
+                        failed_install+=( "${geti}" )
+                    fi
+                done
             fi
-        done
+
+        fi
+
+        [[ -f "${cache}"/registry_wanted_gnome_extensions.txt ]] && rm "${cache}"/registry_wanted_gnome_extensions.txt
+
+        if [[ ! -z ${failed_uninstall+x} && ${#failed_uninstall[@]} -gt 0 ]]; then
+            echo
+            print_char_line '='
+            printf "${BRed}Failed to uninstall:${Color_Off} %d\n" ${#failed_uninstall[@]}
+            printf '%s\n' "${failed_uninstall[@]}"
+        fi
+
+        if [[ ! -z ${failed_install+x} && ${#failed_install[@]} -gt 0 ]]; then
+            echo
+            print_char_line '='
+            printf "${BRed}Failed to install:${Color_Off} %d\n" ${#failed_install[@]}
+            printf '%s\n' "${failed_install[@]}"
+        fi
     fi
-
 fi
-
-[[ -f "${cache}"/registry_wanted_gnome_extensions.txt ]] && rm "${cache}"/registry_wanted_gnome_extensions.txt
-
-if [[ ! -z ${failed_uninstall+x} && ${#failed_uninstall[@]} -gt 0 ]]; then
-    echo
-    print_char_line '='
-    printf "${BRed}Failed to uninstall:${Color_Off} %d\n" ${#failed_uninstall[@]}
-    printf '%s\n' "${failed_uninstall[@]}"
-fi
-
-if [[ ! -z ${failed_install+x} && ${#failed_install[@]} -gt 0 ]]; then
-    echo
-    print_char_line '='
-    printf "${BRed}Failed to install:${Color_Off} %d\n" ${#failed_install[@]}
-    printf '%s\n' "${failed_install[@]}"
-fi
-
 # ------------------------------------------------------------------------------
 
 echo
