Better output

diff --git a/run_onchange_apply_packages.sh.tmpl b/run_onchange_apply_packages.sh.tmpl
--- a/run_onchange_apply_packages.sh.tmpl
+++ b/run_onchange_apply_packages.sh.tmpl
@@ -84,14 +84,35 @@ On_IWhite='\033[0;107m'   # White
 
 # ------------------------------------------------------------------------------
 
-if command -v brew &> /dev/null; then
+executor="${0##*/}"
+executor_path="${BASH_SOURCE}"
+while [ -L "${executor_path}" ]; do
+    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
+    executor_path="$(readlink "${executor_path}")"
+    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
+done
+executor_path="$(readlink -f "${executor_path}")"
+executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"
 
-    printf "\n${BRed}INFO${Color_Off} - Update Homebrew\n"
-    brew update --force
-    brew upgrade
+declare -a required_cmds=( "brew" )
 
-    printf "\n${BRed}INFO${Color_Off} - Installing packages\n"
-    brew bundle install --upgrade --cleanup --file=/dev/stdin <<EOF
+fail=false
+for rc in "${required_cmds[@]}"; do
+    if ! command -v "${rc}" &> /dev/null ; then
+        printf "[${executor}] ${BRed}ERROR${Color_Off} - '${rc}' not available!"
+        fail=true
+    fi
+done
+[[ "${fail}" == true ]] && exit 1
+
+# ------------------------------------------------------------------------------
+
+printf "[${executor}] ${BBlue}INFO${Color_Off} - Update Homebrew...\n"
+brew update --force
+brew upgrade
+
+printf "[${executor}] ${BBlue}INFO${Color_Off} - Installing packages via brew bundle...\n"
+brew bundle install --upgrade --cleanup --file=/dev/stdin <<EOF
 
 {{ range .packages.homebrew.taps -}}
 tap {{ . | quote }}
@@ -127,10 +148,6 @@ vscode {{ . | quote }}
 
 EOF
 
-else
-    printf "${BRed}ERROR${Color_Off} - Homebrew not available!\n"
-fi
-
 # ------------------------------------------------------------------------------
 
 cache=~/.var/lib/chezmoi/run_onchange_apply_packages.d
@@ -158,7 +175,7 @@ EOF
     [[ -f "${cache}"/requirements_previous_pip.txt ]] && rm "${cache}"/requirements_previous_pip.txt
     mv "${cache}"/requirements_current_pip.txt "${cache}"/requirements_previous_pip.txt
 else
-    printf "${BRed}ERROR${Color_Off} - Python pip not available!\n"
+    printf "[${executor}] ${BRed}ERROR${Color_Off} - Python pip not available!\n"
 fi
 
 if command -v gext &> /dev/null; then
@@ -183,13 +200,14 @@ EOF
     [[ -f "${cache}"/requirements_previous_gnome_extentions.txt ]] && rm "${cache}"/requirements_previous_gnome_extentions.txt
     mv "${cache}"/requirements_current_gnome_extentions.txt "${cache}"/requirements_previous_gnome_extentions.txt
 
-    gext update
 else
-    printf "${BRed}ERROR${Color_Off} - Python pip not available!\n"
+    printf "[${executor}] ${BRed}ERROR${Color_Off} - Python pip not available!\n"
 fi
 
 # ------------------------------------------------------------------------------
 
 # sudo usermod -s /usr/bin/xonsh <user>
+
+printf "[${executor}] ${BBlue}INFO${Color_Off} - All done!\n"
 
 {{ end -}}
