Experimental file checks 4

diff --git a/run_onchange_apply_packages.sh.tmpl b/run_onchange_apply_packages.sh.tmpl
--- a/run_onchange_apply_packages.sh.tmpl
+++ b/run_onchange_apply_packages.sh.tmpl
@@ -113,14 +113,18 @@ brew upgrade
 
 printf "\n[${executor}] ${BBlue}INFO${Color_Off} - Evaluating installables via brew bundle...\n"
 
-cat <<EOF | wc -l
+function fail_check {
+    [[ $1 -gt 0 ]] && echo 'FAIL' && exit 1
+}
+
+cat <<EOF | wc -l | fail_check
 {{ range .packages.files -}}
 $(  if [[ ! -f {{ . }} && ! -d {{ . }} ]]; then
         printf "\n[${executor}] ${BBlue}ERROR${Color_Off} - Unable to locate {{ . | quote }} \n"
     fi )
 {{ end -}}
 EOF
-#[[ $fail_lines -gt 0 ]] && echo 'FAIL' && exit 1
+
 
 cat <<EOF
 
