Added removal option and reworked file locations to use podman quadlet install

diff --git a/dot_scripts/executable_setup_quadlet_comfyui b/dot_scripts/executable_setup_quadlet_comfyui
--- a/dot_scripts/executable_setup_quadlet_comfyui
+++ b/dot_scripts/executable_setup_quadlet_comfyui
@@ -107,29 +107,57 @@ done
 
 # ------------------------------------------------------------------------------
 
+REMOVE="false"
+
+usage() {
+    echo "Usage: ${executor} [-h] [-v]" >&2
+}
+
+while getopts ":rh" opt; do
+    case $opt in
+        r) REMOVE="true" ;;
+        h) usage; exit 0 ;;
+        \?) usage; exit 1 ;;
+        :) usage; exit 1 ;;
+    esac
+done
+
+shift $((OPTIND - 1))
+
 app_name="quadlet-comfyui"
-base_image="docker.io/rocm/pytorch:latest"
 
-read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" data_location
+if [[ "${REMOVE}" == "true" ]]; then
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
-mkdir -pv "$HOME/.config/containers/systemd"
-mkdir -pv "$( expand_path "${data_location}" )"{/models,/output,/settings,/tls,/custom_nodes}
-# mkdir -pv "${data_location}"{/models{/diffusion_models,/unet,/vae,/text_encoders,/clip,/checkpoints,/lora},/output,/settings,/workflows,/tls,/custom_nodes}
+    # --force, -f
+    # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
+    # --ignore, -i
+    # Do not error for Quadlets that do not exist.
+    # --recursive
+    # Required when removing applications (default false).
+    podman quadlet rm --force --ignore --recursive -- "${app_name}"
 
-if [[ ! -f "${data_location}/tls/key.pem" || ! -f "${data_location}/tls/cert.pem" ]]; then
-    openssl req -x509 -newkey rsa:4096 \
-        -keyout "${data_location}/tls/key.pem" \
-        -out "${data_location}/tls/cert.pem" \
-        -sha256 -days 3650 -nodes \
-        -subj "/C=CU/ST=${app_name}/L=${app_name}/O=${app_name}/OU=${app_name}/CN=${app_name}"
-fi
+else
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
+    read -e -p "Enter config location:" -i "$HOME/.config/quadlets/data/${app_name}" data_location
 
-ENTRYPOINT='
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
+    mkdir -pv "$HOME/.config/containers/systemd"
+    mkdir -pv "$( expand_path "${data_location}" )"{/models,/output,/settings,/tls,/custom_nodes}
+    # mkdir -pv "${data_location}"{/models{/diffusion_models,/unet,/vae,/text_encoders,/clip,/checkpoints,/lora},/output,/settings,/workflows,/tls,/custom_nodes}
+
+    if [[ ! -f "${data_location}/tls/key.pem" || ! -f "${data_location}/tls/cert.pem" ]]; then
+        openssl req -x509 -newkey rsa:4096 \
+            -keyout "${data_location}/tls/key.pem" \
+            -out "${data_location}/tls/cert.pem" \
+            -sha256 -days 3650 -nodes \
+            -subj "/C=CU/ST=${app_name}/L=${app_name}/O=${app_name}/OU=${app_name}/CN=${app_name}"
+    fi
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
+
+    ENTRYPOINT='
 #!/bin/bash
 set -e
 
@@ -186,24 +214,24 @@ install_node() {
 }
 
 # Uncomment to add nodes:
+install_node "ComfyUI_essentials" "https://github.com/cubiq/ComfyUI_essentials.git"
+install_node "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy.git"
+install_node "ComfyUI-GGUF" "https://github.com/city96/ComfyUI-GGUF.git"
+install_node "ComfyUI-AMDGPUMonitor" "https://github.com/kyuz0/ComfyUI-AMDGPUMonitor.git"
 install_node "ComfyUI-Impact-Pack" "https://github.com/ltdrdata/ComfyUI-Impact-Pack.git"
+install_node "ComfyUI-Crystools" "https://github.com/crystian/ComfyUI-Crystools.git"
+install_node "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes.git"
+install_node "ComfyUI_UltimateSDUpscale" "https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git"
+install_node "ComfyUI-Custom-Scripts" "https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git"
+install_node "Image Size Tool" "https://github.com/TheLustriVA/ComfyUI-Image-Size-Tools.git"
+install_node "CG Use Everywhere" "https://github.com/chrisgoringe/cg-use-everywhere.git"
+install_node "ControlAltAI_Nodes" "https://github.com/gseth/ControlAltAI-Nodes.git"
+
 # install_node "ComfyUI-VideoHelperSuite" "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git"
 # install_node "ComfyUI_IPAdapter_plus" "https://github.com/cubiq/ComfyUI_IPAdapter_plus.git"
 
-# install_node "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
-# install_node "ComfyUI_essentials" "https://github.com/cubiq/ComfyUI_essentials.git"
-install_node "ComfyUI-Crystools" "https://github.com/crystian/ComfyUI-Crystools.git"
-install_node "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy.git"
-install_node "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes.git"
-install_node "ComfyUI_UltimateSDUpscale" "https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git"
-
 # WorkFlow for Flux.dev by Danrisi (txt2img, img2img, upscale and some QoL stuff)
 # https://civitai.com/models/1662914/workflow-for-fluxdev-by-danrisi-txt2img-img2img-upscale-and-some-qol-stuff
-install_node "ComfyUI-Custom-Scripts" "https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git"
-install_node "ComfyUI-GGUF" "https://github.com/city96/ComfyUI-GGUF.git"
-install_node "CG Use Everywhere" "https://github.com/chrisgoringe/cg-use-everywhere.git"
-install_node "ControlAltAI_Nodes" "https://github.com/gseth/ControlAltAI-Nodes.git"
-install_node "Image Size Tool" "https://github.com/TheLustriVA/ComfyUI-Image-Size-Tools.git"
 install_node "ComfyUI-GGUF-FantasyTalking" "https://github.com/kael558/ComfyUI-GGUF-FantasyTalking.git"
 
 # ── Launch ───────────────────────────────────────────────────────────────────
@@ -224,10 +252,10 @@ install_node "ComfyUI-GGUF-FantasyTalking" "https://github.com/kael558/ComfyUI-G
 cd "$COMFYUI_DIR"
 exec python main.py --tls-keyfile "$COMFYUI_DIR"/tls/key.pem --tls-certfile "$COMFYUI_DIR"/tls/cert.pem --listen 0.0.0.0 ${CLI_ARGS}
 '
-echo "${ENTRYPOINT}" | tee "${data_location}/${app_name}.entrypoint" > /dev/null
+    echo "${ENTRYPOINT}" | tee "${data_location}/${app_name}.entrypoint" > /dev/null
 
-CONTAINERFILE="
-FROM ${base_image}
+    CONTAINERFILE="
+FROM docker.io/rocm/pytorch:latest
 
 # System dependencies
 RUN apt-get update && apt-get install -y \
@@ -245,19 +273,20 @@ EXPOSE 8188
 
 ENTRYPOINT ["/entrypoint.sh"]
 "
-echo "${CONTAINERFILE}" | tee "$HOME/.config/containers/systemd/${app_name}.Containerfile" > /dev/null
+    echo "${CONTAINERFILE}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.Containerfile" > /dev/null
 
-BUILD="
+    BUILD="
 [Build]
 ImageTag=localhost/${app_name}:latest
 File=${app_name}.Containerfile
 SetWorkingDirectory=unit
 "
-echo "${BUILD}" | tee "$HOME/.config/containers/systemd/${app_name}.build" > /dev/null
+    echo "${BUILD}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.build" > /dev/null
 
-CONTAINER="
+    CONTAINER="
 [Unit]
 Description=${app_name}
+Wants=network-online.target
 After=network-online.target
 # Limit to 5 restart attempts within a 60 second window
 StartLimitIntervalSec=60
@@ -310,19 +339,24 @@ TimeoutStopSec=30
 [Install]
 WantedBy=multi-user.target default.target
 "
-echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null
+    echo "${CONTAINER}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.container" > /dev/null
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
-systemctl --user daemon-reload
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Installing quadlet...\n"
+    podman quadlet install --replace --application=${app_name} "$HOME/.config/quadlets/init/${app_name}/"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
-systemctl --user restart "${app_name}"
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
+    # systemctl --user daemon-reload
 
-# Start user services even when not logged in
-loginctl enable-linger $USER
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
+    # systemctl --user restart "${app_name}"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
-# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
-# manually by calling 'podman auto-update'
-# or automatically by enabling the relative systemd service:
-systemctl enable --user --now podman-auto-update.timer
+    # Start user services even when not logged in
+    loginctl enable-linger $USER
+
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
+    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
+    # manually by calling 'podman auto-update'
+    # or automatically by enabling the relative systemd service:
+    systemctl enable --user --now podman-auto-update.timer
+
+fi
diff --git a/dot_scripts/executable_setup_quadlet_invokeai b/dot_scripts/executable_setup_quadlet_invokeai
--- a/dot_scripts/executable_setup_quadlet_invokeai
+++ b/dot_scripts/executable_setup_quadlet_invokeai
@@ -107,27 +107,59 @@ done
 
 # ------------------------------------------------------------------------------
 
-app_name="invokeai"
-base_image="ghcr.io/invoke-ai/invokeai:main-rocm"
+REMOVE="false"
 
-read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" config_location
-config_location="$( expand_path "${config_location}" )"
+usage() {
+    echo "Usage: ${executor} [-h] [-v]" >&2
+}
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
-mkdir -pv "$HOME/.config/containers/systemd"
-mkdir -pv "${config_location}"
+while getopts ":rh" opt; do
+    case $opt in
+        r) REMOVE="true" ;;
+        h) usage; exit 0 ;;
+        \?) usage; exit 1 ;;
+        :) usage; exit 1 ;;
+    esac
+done
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
-CONTAINER="
+shift $((OPTIND - 1))
+
+app_name="quadlet-invokeai"
+
+if [[ "${REMOVE}" == "true" ]]; then
+
+    # --force, -f
+    # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
+    # --ignore, -i
+    # Do not error for Quadlets that do not exist.
+    # --recursive
+    # Required when removing applications (default false).
+    podman quadlet rm --force --ignore --recursive -- "${app_name}"
+
+else
+
+    read -e -p "Enter config location:" -i "$HOME/.config/quadlets/data/${app_name}" config_location
+    config_location="$( expand_path "${config_location}" )"
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
+    mkdir -pv "$HOME/.config/containers/systemd"
+    mkdir -pv "${config_location}"
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
+    CONTAINER="
 [Unit]
-Description=${app_name} quadlet
+Description=${app_name}
+Wants=network-online.target
 After=network-online.target
+# Limit to 5 restart attempts within a 60 second window
+StartLimitIntervalSec=60
+StartLimitBurst=5
 
 [Container]
 ContainerName=${app_name}
-Image=${base_image}
+Image=ghcr.io/invoke-ai/invokeai:main-rocm
 PublishPort=8189:9090
 Volume=${config_location}:/invokeai:Z
 SeccompProfile=unconfined
@@ -148,19 +180,23 @@ TimeoutStartSec=900
 [Install]
 WantedBy=multi-user.target default.target
 "
-echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null
+    echo "${CONTAINER}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.container" > /dev/null
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
-systemctl --user daemon-reload
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Installing quadlet...\n"
+    podman quadlet install --replace --application=${app_name} "$HOME/.config/quadlets/init/${app_name}/"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
-systemctl --user restart "${app_name}"
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
+    # systemctl --user daemon-reload
 
-# Start user services even when not logged in
-loginctl enable-linger $USER
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
+    # systemctl --user restart "${app_name}"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
-# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
-# manually by calling 'podman auto-update'
-# or automatically by enabling the relative systemd service:
-systemctl enable --user --now podman-auto-update.timer
+    # Start user services even when not logged in
+    loginctl enable-linger $USER
+
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
+    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
+    # manually by calling 'podman auto-update'
+    # or automatically by enabling the relative systemd service:
+    systemctl enable --user --now podman-auto-update.timer
+fi
diff --git a/dot_scripts/executable_setup_quadlet_miniserve b/dot_scripts/executable_setup_quadlet_miniserve
--- a/dot_scripts/executable_setup_quadlet_miniserve
+++ b/dot_scripts/executable_setup_quadlet_miniserve
@@ -107,32 +107,64 @@ done
 
 # ------------------------------------------------------------------------------
 
-app_name="miniserve"
-base_image="docker.io/svenstaro/miniserve"
+REMOVE="false"
 
-read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" data_location
-data_location="$( expand_path "${data_location}" )"
-read -e -p "Enter shared location:" -i "$HOME/.shared_by_${app_name}.d" shared_location
-shared_location="$( expand_path "${shared_location}" )"
+usage() {
+    echo "Usage: ${executor} [-h] [-v]" >&2
+}
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
-mkdir -pv "$HOME/.config/containers/systemd"
-mkdir -pv "${data_location}"
-mkdir -pv "${shared_location}"
+while getopts ":rh" opt; do
+    case $opt in
+        r) REMOVE="true" ;;
+        h) usage; exit 0 ;;
+        \?) usage; exit 1 ;;
+        :) usage; exit 1 ;;
+    esac
+done
 
-[[ ! -f "${data_location}/tls/key.pem" || ! -f "${data_location}/tls/cert.pem" ]] && openssl req -x509 -newkey rsa:4096 -keyout "${data_location}/tls/key.pem" -out "${data_location}/tls/cert.pem" -sha256 -days 3650 -nodes -subj "/C=CU/ST=${app_name}/L=${app_name}/O=${app_name}/OU=${app_name}/CN=${app_name}"
+shift $((OPTIND - 1))
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
-CONTAINER="
+app_name="quadlet-miniserve"
+
+if [[ "${REMOVE}" == "true" ]]; then
+
+    # --force, -f
+    # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
+    # --ignore, -i
+    # Do not error for Quadlets that do not exist.
+    # --recursive
+    # Required when removing applications (default false).
+    podman quadlet rm --force --ignore --recursive -- "${app_name}"
+
+else
+
+    read -e -p "Enter config location:" -i "$HOME/.config/quadlets/data/${app_name}" data_location
+    data_location="$( expand_path "${data_location}" )"
+    read -e -p "Enter shared location:" -i "$HOME/.miniserve.d" shared_location
+    shared_location="$( expand_path "${shared_location}" )"
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
+    mkdir -pv "$HOME/.config/containers/systemd"
+    mkdir -pv "${data_location}"
+    mkdir -pv "${shared_location}"
+
+    [[ ! -f "${data_location}/tls/key.pem" || ! -f "${data_location}/tls/cert.pem" ]] && openssl req -x509 -newkey rsa:4096 -keyout "${data_location}/tls/key.pem" -out "${data_location}/tls/cert.pem" -sha256 -days 3650 -nodes -subj "/C=CU/ST=${app_name}/L=${app_name}/O=${app_name}/OU=${app_name}/CN=${app_name}"
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
+    CONTAINER="
 [Unit]
 Description=${app_name} quadlet
+Wants=network-online.target
 After=network-online.target
+# Limit to 5 restart attempts within a 60 second window
+StartLimitIntervalSec=60
+StartLimitBurst=5
 
 [Container]
 ContainerName=${app_name}
-Image=${base_image}
+Image=docker.io/svenstaro/miniserve
 PublishPort=8080:8080
 AutoUpdate=registry
 
@@ -164,19 +196,23 @@ TimeoutStartSec=900
 [Install]
 WantedBy=multi-user.target default.target
 "
-echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null
+    echo "${CONTAINER}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.container" > /dev/null
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
-systemctl --user daemon-reload
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Installing quadlet...\n"
+    podman quadlet install --replace --application=${app_name} "$HOME/.config/quadlets/init/${app_name}/"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
-systemctl --user restart "${app_name}"
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
+    # systemctl --user daemon-reload
 
-# Start user services even when not logged in
-loginctl enable-linger $USER
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
+    # systemctl --user restart "${app_name}"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
-# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
-# manually by calling 'podman auto-update'
-# or automatically by enabling the relative systemd service:
-systemctl enable --user --now podman-auto-update.timer
+    # Start user services even when not logged in
+    loginctl enable-linger $USER
+
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
+    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
+    # manually by calling 'podman auto-update'
+    # or automatically by enabling the relative systemd service:
+    systemctl enable --user --now podman-auto-update.timer
+fi
diff --git a/dot_scripts/executable_setup_quadlet_syncthing b/dot_scripts/executable_setup_quadlet_syncthing
--- a/dot_scripts/executable_setup_quadlet_syncthing
+++ b/dot_scripts/executable_setup_quadlet_syncthing
@@ -107,34 +107,67 @@ done
 
 # ------------------------------------------------------------------------------
 
+REMOVE="false"
+
+usage() {
+    echo "Usage: ${executor} [-h] [-v]" >&2
+}
+
+while getopts ":rh" opt; do
+    case $opt in
+        r) REMOVE="true" ;;
+        h) usage; exit 0 ;;
+        \?) usage; exit 1 ;;
+        :) usage; exit 1 ;;
+    esac
+done
+
+shift $((OPTIND - 1))
+
 app_name="syncthing"
 
-read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" config_location
-config_location="$( expand_path "${config_location}" )"
-read -e -p "Enter shares location:" -i "$HOME/${app_name}" shares_location
-shares_location="$( expand_path "${shares_location}" )"
-read -e -p "Timezone:" -i "$(timedatectl show -P Timezone)" time_zone
+if [[ "${REMOVE}" == "true" ]]; then
 
-# $( whoami ) or $( id -un ) for current user
-local_user_uid=$( id -u ) # or $( id -u <username> ) for any other user than current
-local_user_gid=$( id -g ) # or $( id -g <username> ) for any other user than current
+    # --force, -f
+    # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
+    # --ignore, -i
+    # Do not error for Quadlets that do not exist.
+    # --recursive
+    # Required when removing applications (default false).
+    podman quadlet rm --force --ignore --recursive -- "${app_name}"
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
-mkdir -pv "$HOME/.config/containers/systemd"
-mkdir -pv "${config_location}"
-mkdir -pv "${shares_location}"
+else
 
-echo
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
-CONTAINER="
+    read -e -p "Enter config location:" -i "$HOME/.config/quadlets/data/${app_name}" config_location
+    config_location="$( expand_path "${config_location}" )"
+    read -e -p "Enter shares location:" -i "$HOME/.syncthing.d" shares_location
+    shares_location="$( expand_path "${shares_location}" )"
+    read -e -p "Timezone:" -i "$(timedatectl show -P Timezone)" time_zone
+
+    # $( whoami ) or $( id -un ) for current user
+    read -e -p "UID:" -i "$( id -u )" local_user_uid # or $( id -u <username> ) for any other user than current
+    read -e -p "GID:" -i "$( id -g )" local_user_gid # or $( id -g <username> ) for any other user than current
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
+    # mkdir -pv "$HOME/.config/containers/systemd"
+    mkdir -pv "$HOME/.config/quadlets/init/${app_name}"
+    mkdir -pv "${config_location}"
+    mkdir -pv "${shares_location}"
+
+    echo
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Generating quadlet...\n"
+    CONTAINER="
 [Unit]
 Description=${app_name} quadlet
 Wants=network-online.target
 After=network-online.target
+# Limit to 5 restart attempts within a 60 second window
+StartLimitIntervalSec=60
+StartLimitBurst=5
 
 [Container]
-ContainerName=${app_name}
+ContainerName=quadlet-${app_name}
 Image=docker.io/syncthing/syncthing:latest
 
 # Podman automatic updates
@@ -180,7 +213,7 @@ LogDriver=k8s-file
 PodmanArgs=--log-opt=max-size=10m --log-opt=max-file=3
 
 [Service]
-Restart=unless-stopped
+Restart=always
 RestartSec=5
 # Give image pulls/builds enough time during startup
 TimeoutStartSec=900
@@ -188,21 +221,25 @@ TimeoutStartSec=900
 [Install]
 WantedBy=default.target
 "
-echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null
+    echo "${CONTAINER}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.container" > /dev/null
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
-systemctl --user daemon-reload
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Installing quadlet...\n"
+    podman quadlet install --replace --application=${app_name} "$HOME/.config/quadlets/init/${app_name}/"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
-systemctl --user restart "${app_name}"
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
+    # systemctl --user daemon-reload
 
-# Start user services even when not logged in
-loginctl enable-linger $USER
+    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
+    # systemctl --user restart "${app_name}"
 
-printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
-# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
-# manually by calling 'podman auto-update'
-# or automatically by enabling the relative systemd service:
-systemctl enable --user --now podman-auto-update.timer
+    # Start user services even when not logged in
+    loginctl enable-linger $USER
 
-printf "[${executor}] ${BGreen}DONE${Color_Off} - Check logs with: podman logs -tf ${app_name}\n"
+    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
+    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
+    # manually by calling 'podman auto-update'
+    # or automatically by enabling the relative systemd service:
+    systemctl enable --user --now podman-auto-update.timer
+
+    printf "[${executor}] ${BGreen}DONE${Color_Off} - Check logs with: podman logs -tf quadlet-${app_name}\n"
+fi
